apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    name: chetan-rns
  name: sample
---
apiVersion: v1
data:
  index.html: |+
    <!DOCTYPE html>
    <html>
    <head>
    <title>Dev Environment</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body>
    <h1>Book Taxi - Dev Environment</h1>
    <p>This is the page content from the Chetan!</p>
    </body>
    </html>

kind: ConfigMap
metadata:
  labels:
    name: chetan-rns
  name: www-files-8fm9hdg6f7
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: taxi
    app.kubernetes.io/version: 0.0.1
    name: chetan-rns
  name: taxi
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: taxi
    app.kubernetes.io/version: 0.0.1
    name: chetan-rns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: taxi
    app.kubernetes.io/version: 0.0.1
    name: chetan-rns
  name: taxi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: taxi
      app.kubernetes.io/version: 0.0.1
      name: chetan-rns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: taxi
        app.kubernetes.io/version: 0.0.1
        name: chetan-rns
    spec:
      containers:
      - image: quay.io/cbanavik/taxi
        imagePullPolicy: Always
        name: taxi-2
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/booktaxi
          name: web-files
      volumes:
      - configMap:
          name: www-files-8fm9hdg6f7
        name: web-files
